### ISSUE TITLE
win32-taskscheduler issues with puppet

### ISSUE THREAD

**Issue by lc0** [djberg96/win32-taskscheduler#10]
Hi guys,

I'm trying to use puppet for provisioning my Windows VM. 
The configuration is prettty simple, i have it as an example from docs:

``` Puppet
scheduled_task { 'An every-other-day task':
      ensure    => present,
      enabled   => true,
      command   => 'C:\path\to\command.exe',
      arguments => '/flags /to /pass',
      trigger   => {
        schedule   => daily,
        start_time => '08:00',      # Must be specified
      },
    }
```

The problem that with gem version **0.2.2** it fails with message. I documentation Puppetlabs say, that should not be the issue if gem is older than **0.2.1**, but it doesn't work for me:

```
Error: /Stage[main]/Main/Node[win-test]/Scheduled_task[A n every-other-day task]: Could not evaluate: The operation completed successfully.
```

I've tried to updated to 0.3.1 and 0.3.0, but with this version it doesn't look like backward compatible:

```
Error: Could not set 'present' on ensure: start_year must be set at 17:c:/test.pp
Error: Could not set 'present' on ensure: start_year must be set at 17:c:/test.pp
Wrapped exception:
start_year must be set
Error: /Stage[main]/Main/Node[win-test]/Scheduled_task[An every-other-day task]/ensure: change from absent to present failed: Could not
set 'present' on ensure: start_year must be set at 17:c:/test.pp
Notice: Finished catalog run in 0.34 seconds
```

also if i try to add **start_year** it fails in another way:

```
Error: Parameter trigger failed on Scheduled_task[An every-other-day task]: Unknown trigger option(s): ['start_year'] at c:/test.pp:18
Wrapped exception:
Unknown trigger option(s): ['start_year']
```

Thanks for the help!

**Comment by djberg96** [comment]
@lc0 Sorry for the long delay. Did you ever get this worked out?

**Comment by lc0** [comment]
It was quite some time ago, we do not use Windows for that anymore. 
On the other hand, we had it fixed, just it's very hard to find out what was the reason.

If anybody still has any issues with that, I might try to find a configuration that I used last time.

Cheers,
Sergii
